### ISSUE TITLE
Reflection: number params can't be 0

### ISSUE THREAD

**Issue by sami-avangrade** [seratch/apriori.js#2]
My problem is if I set param minSupport or minConfidence to 0 or 0.0 then they will be set to 0.15 and 0.6.

apriori.js:
47.    this.minSupport = minSupport || 0.15;
48.    this.minConfidence = minConfidence || 0.6;

My solution:
this.minSupport = minSupport ? minSupport : minSupport == 0 ? 0 : 0.15;
this.minConfidence = minConfidence ? minConfidence : minConfidence == 0 ? 0 : 0.6;

I don't know if it is the standard functioning of apriori algorithm so I don't know if it is a bug or not.

**Comment by seratch** [comment]
Thanks. Actually specifying zero is not useful but that should be possible. I just fixed and published 1.0.7.

**Comment by sami-avangrade** [comment]
Okey. Thanks.
