### ISSUE TITLE
How to compile apriori.min.js when I modify apriori.js or apriori.ts

### ISSUE THREAD

**Issue by howel52** [seratch/apriori.js#4]
I want to add functionality to the repos, but When I modify the apriori.js or apriori.ts, I dont find the way how to compile the apriori.min.js.

**Comment by howel52** [comment]
My changes are [here ](https://github.com/howel52/apriori.js/commit/1025d467fa9b7d560510e8b68e5665a6de23ec4b)

**Comment by seratch** [comment]
As I described in README, `grunt build` should work as you expect.

**Comment by howel52** [comment]
When I run 'grunt build',  show these errors



`Running "typescript:base" (typescript) task
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(6,9):
>> error TS1005: ';' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(6,19):
>> error TS1005: ';' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(6,25):
>> error TS1005: ';' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(8,3):
>> error TS1008: Unexpected token; 'statement' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(13,10):
>> error TS1005: ';' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(13,11):
>> error TS1008: Unexpected token; 'constructor, function, accessor or variable' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(191,55):
>> error TS1008: Unexpected token; 'parameter' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(191,87):
>> error TS1005: ';' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(191,95):
>> error TS1005: ';' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(191,109):
>> error TS1005: ';' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(191,110):
>> error TS1008: Unexpected token; 'constructor, function, accessor or variable' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(191,112):
>> error TS1008: Unexpected token; 'constructor, function, accessor or variable' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(191,115):
>> error TS1005: ';' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(191,116):
>> error TS1008: Unexpected token; 'module, class, interface, enum, import or statement' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(192,17):
>> error TS1005: ',' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(192,39):
>> error TS1003: Identifier expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(192,62):
>> error TS1003: Identifier expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(192,68):
>> error TS1005: ';' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(200,28):
>> error TS1003: Identifier expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(200,38):
>> error TS1005: ';' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(208,15):
>> error TS1005: ',' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(208,24):
>> error TS1003: Identifier expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(208,26):
>> error TS1005: ';' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(216,22):
>> error TS1005: ',' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(216,31):
>> error TS1003: Identifier expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(216,33):
>> error TS1005: ';' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(223,11):
>> error TS1005: ';' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(223,19):
>> error TS1005: ',' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(223,28):
>> error TS1005: ';' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(231,20):
>> error TS1005: ',' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(231,29):
>> error TS1005: ';' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(232,18):
>> error TS1005: ';' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(240,16):
>> error TS1005: ',' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(240,25):
>> error TS1005: ';' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(241,12):
>> error TS1005: ';' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(249,14):
>> error TS1005: ',' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(249,23):
>> error TS1005: ';' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(250,12):
>> error TS1005: ';' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(258,13):
>> error TS1005: ',' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(258,22):
>> error TS1005: ';' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(265,11):
>> error TS1005: ';' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(272,19):
>> error TS1003: Identifier expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(272,45):
>> error TS1005: ';' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(272,51):
>> error TS1003: Identifier expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(278,13):
>> error TS1003: Identifier expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(278,39):
>> error TS1005: ';' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(278,45):
>> error TS1003: Identifier expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(279,3):
>> error TS1008: Unexpected token; 'module, class, interface, enum, import or statement' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(281,1):
>> error TS1008: Unexpected token; 'module, class, interface, enum, import or statement' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(283,9):
>> error TS1005: ';' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(283,19):
>> error TS1005: ';' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(283,29):
>> error TS1005: ';' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(285,10):
>> error TS1005: ';' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(287,10):
>> error TS1005: ';' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(289,5):
>> error TS1008: Unexpected token; 'statement' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(306,1):
>> error TS1008: Unexpected token; 'module, class, interface, enum, import or statement' expected.
>> /Users/bytedance/howel/apriori-pro/node_modules/har-validator/node_modules/commander/typings/index.d.ts(308,9):
>> error TS1005: ';' expected.
Warning: Task "typescript:base" failed. Use --force to continue.

Aborted due to warnings.`


tsc 2.9.1
tsd 0.6.5
